services:
  frontend:
    build:
      context: ./frontend/register_app 
    ports:
      - "5173:80"        
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  
    ports:
      - "5000:5000"      
    environment:
      - MONGO_URI=mongodb+srv://dipakkarmur45:Ahir123%40@cluster0.msg6j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:5      
    ports:
      - "27017:27017"    
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
